### ISSUE TITLE
Can't find file 'create-alternative-alleles.py' and 'process-sample.py'

### ISSUE THREAD

**Issue by oldteng** [clemgoub/reGenotypeTE#1]
Hi, I tried to run TypeTE following your instruction. The log said,

> python2.7: can't open file 'insertion-genotype/create-alternative-alleles.py': [Errno 2] No such file or directory
>python2.7: can't open file 'insertion-genotype/process-sample.py': [Errno 2] No such file or directory

I don't know whether these python programs were lost. I also wonder if the python programs were generated in the former processes. If so, which process generates these programs?

**Comment by xuxif** [comment]
Me too.

**Comment by clemgoub** [comment]
Sorry guys, I fixed this!
Try to pull again the master branch:

`git clone --recurse-submodules https://github.com/clemgoub/TypeTE.git
`

We are working on a docker container, will be available with L1 and SVA support soon!
