### ISSUE TITLE
Can TypeTE be used for genotyping other types of TE at present？

### ISSUE THREAD

**Issue by yinmou21** [clemgoub/reGenotypeTE#3]
Hello，

You mentioned something about TypeTE use：

_“Currently TypeTE is working only with Alu insertions in the human genome but will be soon available for L1, SVA as well as virtualy any retrotransposon in any organism with a reference genome.”_

**I would like to know whether TypeTE can be used for genotyping other types of TE at present.**

Thank you and look forward to your reply！

**Comment by clemgoub** [comment]
Hello Yinmou21,

We have indeed added the possibility to genotype L1 and SVA for **reference TE only**. This is now available with [TypeREF](https://github.com/clemgoub/typeref).

For the genotyping of non-reference L1 and SVA, I suggest to take a look at [MELT2](https://melt.igs.umaryland.edu/), [ERVcaller](https://academic.oup.com/bioinformatics/article/35/20/3913/5416145?login=true) or [xTEA](https://github.com/parklab/xTea).

Best,

Clément
