### ISSUE TITLE
how to understand the output, MELT result as input

### ISSUE THREAD

**Issue by GGBond178** [clemgoub/reGenotypeTE#5]
we used the melt output file as input.

the output folder include

```
samples
RM_intervals.out
output_TSD_Intervals.out
locusAlleles
genotyping_logs
RM_insertions_TSD_strands
OUTPUTS_Ref_testdata.TypeTE.vcf.gz
OUTPUTS_Ref_testdata.input
OUTPUTS_Ref_testdata.allele

```

how to understand the output? for example, `OUTPUTS_Ref_testdata.TypeTE.vcf.gz` file, how to know if the allele "PASS" the QC or not？

The original MELT output has `QUAL` column.

**Comment by clemgoub** [comment]
Hello!

We did not implement specific QC filters with TypeTE. However you should have access to the number of reads mapped per allele. Could you post 1-2 lines of your ouput VCF, so I can point you to it?

Note that if you are working with reference loci, I recommend you to use TypeREF, that should be more streamlined and also allows you to deal with L1 and SVA. https://github.com/clemgoub/typeref -- we have a tutorial available here: https://link.springer.com/protocol/10.1007/978-1-0716-2883-6_4

Best,

Clément

**Comment by GGBond178** [comment]
Thank you  for your valuable guidance!The issue I previously encountered has been successfully resolved.

Best,

Yue
